"""Initial database schema

Revision ID: d17b62e2016a
Revises: 
Create Date: 2025-10-05 01:14:36.167234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17b62e2016a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('HACKATHON', 'WEBINAR', 'WORKSHOP', 'COMPETITION', 'CONFERENCE', name='eventtype'), nullable=False),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('registration_url', sa.String(length=500), nullable=True),
    sa.Column('is_registration_open', sa.Boolean(), nullable=True),
    sa.Column('prizes', sa.JSON(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_registration_deadline'), 'events', ['registration_deadline'], unique=False)
    op.create_index(op.f('ix_events_start_date'), 'events', ['start_date'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('JOB', 'INTERNSHIP', 'HACKATHON', 'SCHOLARSHIP', 'FELLOWSHIP', name='opportunitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('skills_required', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('stipend', sa.String(length=100), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_category'), 'opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_opportunities_company'), 'opportunities', ['company'], unique=False)
    op.create_index(op.f('ix_opportunities_deadline'), 'opportunities', ['deadline'], unique=False)
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_opportunities_is_active'), 'opportunities', ['is_active'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_index(op.f('ix_opportunities_type'), 'opportunities', ['type'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'ARTICLE', 'COURSE', 'BOOK', 'TUTORIAL', 'DOCUMENTATION', name='resourcetype'), nullable=False),
    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_curated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_difficulty'), 'resources', ['difficulty'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth0_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=500), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('specialization', sa.String(length=255), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('profile_completion', sa.Integer(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_auth0_id'), 'users', ['auth0_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('career_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('growth_potential', sa.String(length=50), nullable=True),
    sa.Column('learning_roadmap', sa.JSON(), nullable=True),
    sa.Column('estimated_time', sa.String(length=100), nullable=True),
    sa.Column('is_saved', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_id'), 'career_paths', ['id'], unique=False)
    op.create_index(op.f('ix_career_paths_user_id'), 'career_paths', ['user_id'], unique=False)
    op.create_table('mental_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood_rating', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('check_in_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('detected_concerns', sa.JSON(), nullable=True),
    sa.Column('ai_suggestions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mental_health_logs_created_at'), 'mental_health_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_mental_health_logs_id'), 'mental_health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mental_health_logs_user_id'), 'mental_health_logs', ['user_id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_role', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('expertise_areas', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('industries', sa.JSON(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('mentoring_capacity', sa.Integer(), nullable=True),
    sa.Column('current_mentees', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('preferred_communication', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'INACTIVE', name='mentorstatus'), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_index(op.f('ix_mentors_status'), 'mentors', ['status'], unique=False)
    op.create_index(op.f('ix_mentors_user_id'), 'mentors', ['user_id'], unique=True)
    op.create_table('saved_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_opportunities_id'), 'saved_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_opportunity_id'), 'saved_opportunities', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_saved_opportunities_user_id'), 'saved_opportunities', ['user_id'], unique=False)
    op.create_table('skill_gap_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('current_skills', sa.JSON(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('missing_skills', sa.JSON(), nullable=True),
    sa.Column('skill_gaps', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gap_analyses_id'), 'skill_gap_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gap_analyses_user_id'), 'skill_gap_analyses', ['user_id'], unique=False)
    op.create_table('mentorship_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='connectionstatus'), nullable=True),
    sa.Column('request_message', sa.Text(), nullable=True),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('next_session', sa.DateTime(), nullable=True),
    sa.Column('student_feedback', sa.Text(), nullable=True),
    sa.Column('mentor_feedback', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorship_connections_id'), 'mentorship_connections', ['id'], unique=False)
    op.create_index(op.f('ix_mentorship_connections_mentor_id'), 'mentorship_connections', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_mentorship_connections_status'), 'mentorship_connections', ['status'], unique=False)
    op.create_index(op.f('ix_mentorship_connections_student_id'), 'mentorship_connections', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorship_connections_student_id'), table_name='mentorship_connections')
    op.drop_index(op.f('ix_mentorship_connections_status'), table_name='mentorship_connections')
    op.drop_index(op.f('ix_mentorship_connections_mentor_id'), table_name='mentorship_connections')
    op.drop_index(op.f('ix_mentorship_connections_id'), table_name='mentorship_connections')
    op.drop_table('mentorship_connections')
    op.drop_index(op.f('ix_skill_gap_analyses_user_id'), table_name='skill_gap_analyses')
    op.drop_index(op.f('ix_skill_gap_analyses_id'), table_name='skill_gap_analyses')
    op.drop_table('skill_gap_analyses')
    op.drop_index(op.f('ix_saved_opportunities_user_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_opportunity_id'), table_name='saved_opportunities')
    op.drop_index(op.f('ix_saved_opportunities_id'), table_name='saved_opportunities')
    op.drop_table('saved_opportunities')
    op.drop_index(op.f('ix_mentors_user_id'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_status'), table_name='mentors')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_mental_health_logs_user_id'), table_name='mental_health_logs')
    op.drop_index(op.f('ix_mental_health_logs_id'), table_name='mental_health_logs')
    op.drop_index(op.f('ix_mental_health_logs_created_at'), table_name='mental_health_logs')
    op.drop_table('mental_health_logs')
    op.drop_index(op.f('ix_career_paths_user_id'), table_name='career_paths')
    op.drop_index(op.f('ix_career_paths_id'), table_name='career_paths')
    op.drop_table('career_paths')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_difficulty'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_opportunities_type'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_is_active'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_deadline'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_company'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_registration_deadline'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
